#!/bin/bash

echo "🚀 PSIP Navigator - Netlify Deployment Script"
echo "=============================================="
echo ""

# Step 1: Deploy Backend to Railway
echo "📦 Step 1: Deploy Backend to Railway"
echo "------------------------------------"
echo "1. Go to https://railway.app"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New Project' → 'Deploy from GitHub repo'"
echo "4. Select your 'psip-navigator-full' repository"
echo "5. Railway will auto-detect it's a Python project"
echo ""
echo "6. Set these Environment Variables in Railway:"
echo "   OPENAI_API_KEY=your_openai_key_here"
echo "   CHROMA_PATH=/tmp/chroma_db"
echo "   COLLECTION_NAME=benefits_documents"
echo "   EMBEDDING_MODEL=all-MiniLM-L6-v2"
echo "   OPENAI_MODEL=gpt-4o-mini"
echo ""
echo "7. Wait for deployment to complete"
echo "8. Copy your Railway URL (e.g., https://psip-navigator-production.railway.app)"
echo ""
read -p "Press Enter when Railway backend is deployed and you have the URL..."

# Get Railway URL
echo ""
echo "Enter your Railway backend URL:"
read RAILWAY_URL

# Step 2: Deploy Frontend to Netlify
echo ""
echo "🌐 Step 2: Deploy Frontend to Netlify"
echo "-------------------------------------"
echo "1. Go to https://netlify.com"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New site from Git' → 'GitHub'"
echo "4. Select your 'psip-navigator-full' repository"
echo "5. Configure build settings:"
echo "   - Base directory: psip-plan-pal"
echo "   - Build command: npm run build"
echo "   - Publish directory: psip-plan-pal/dist"
echo ""
echo "6. Add Environment Variable:"
echo "   VITE_API_BASE_URL=$RAILWAY_URL"
echo ""
echo "7. Click 'Deploy site'"
echo ""
read -p "Press Enter when Netlify frontend is deployed..."

# Step 3: Update CORS
echo ""
echo "🔧 Step 3: Update CORS Settings"
echo "-------------------------------"
echo "1. Go back to your Railway project"
echo "2. Add this Environment Variable:"
echo "   ALLOWED_ORIGINS=https://your-netlify-site.netlify.app"
echo "3. Railway will automatically redeploy"
echo ""
echo "4. Test your deployment:"
echo "   - Visit your Netlify URL"
echo "   - Test both Nelly 1.0 and GPT-4 models"
echo "   - Check that responses are working"
echo ""

echo "✅ Deployment Complete!"
echo "======================"
echo "Your PSIP Navigator is now live!"
echo "Frontend: https://your-netlify-site.netlify.app"
echo "Backend: $RAILWAY_URL"
echo ""
echo "🎉 Share your app with users!"
